### ISSUE TITLE
User/topic refiner and reddit data

### ISSUE THREAD

**Issue by lslightquantum** [bangbangbang12315/MSP#3]
Hi, thank you for the great work! I'm trying to replicate the result with my own data, but I'm not very clear about the user refiner and the topic refiner. Could you publish the code for these two refiners? Thank you!

Also, could you publish the Reddit data (before refinement) used in you paper? Thank you!

**Comment by WilliamsToTo** [comment]
I meet the same problem. It will be great if the author can publish Reddit data.

**Comment by bangbangbang12315** [comment]
The user/topic refining process is like a data preprocess so that we split them with our model code and didn't put them into our Github repo. After we re-collating the user/topic refiner code, we will update the repo. 
For the Reddit data, we collate them from the open source way and filter and clean them. For your request, https://files.pushshift.io/reddit/submissions may be useful.

**Comment by WilliamsToTo** [comment]
Thank you for your response. I'm looking forward to your code and data. Also, for the Reddit dataset, which exact file did you use in your paper? Can you tell me the filename?

**Comment by bangbangbang12315** [comment]
The Reddit data is is sorted by time. Our Reddit dataset is extracted from comment chains scraped from Dec. 1, 2015 to Oct. 30, 2018.
